### ISSUE TITLE
Issue #1

### ISSUE THREAD

**Issue by squirrelsquirrel78** [HongSenDu/TeamHope-DIYVentilatorChallenge#1]
[Github Selfies](https://chrome.google.com/webstore/detail/github-selfies/ldnpkdnkgkogfnahcnldaedcoadjbkbl)

**Comment by shallotly** [comment]
qt

**Comment by squirrelsquirrel78** [comment]
![image](https://user-images.githubusercontent.com/15334952/78620827-016ea780-784f-11ea-9ff7-bc6899f534be.png)

**Comment by squirrelsquirrel78** [comment]
![image](https://user-images.githubusercontent.com/15334952/78624811-84483000-7858-11ea-8133-c70c8333b5fd.png)

**Comment by shallotly** [comment]
![20799033_831362447040415_6602392426379334233_n](https://user-images.githubusercontent.com/56002814/78624912-c40f1780-7858-11ea-8f95-b2e5ab3e3a6c.jpg)

**Comment by squirrelsquirrel78** [comment]
Still not resolved
